version: '3.1'

services:
  zikm:
    build: ./..
    restart: always
    environment:
      Storage: InternalDB
    volumes: 
      - ./AppData/Data:/app/DB
      - ./Logs:/app/Logs
    ports:
      - 8000:8000