version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: CHANGE-ME-BEFORE-RUN
      MYSQL_DATABASE: ZikmDB
    volumes: 
      - ./AppData/Data:/var/lib/mysql

  zikm:
    build: ./..
    restart: always
    environment:
        Storage: ExternalDB
        Server: db
        Password: CHANGE-ME-BEFORE-RUN
    volumes: 
      - ./Logs:/app/Logs
    ports:
      - 8000:8000
    depends_on: 
      - db